### ISSUE TITLE
Add option to remove stage from custom dns path

### ISSUE THREAD

**Issue by seantibor** [mondelez-ctiso/terraform-aws-api-gateway-v1#11]
It is sometimes desirable to remove the api stage from the path of the url, especially when publishing an endpoint for external consumers. Additionally, we rarely have multiple sdlc stages defined in the same account. For example, prod gateways usually do not have nonprod stages available in the same account to prevent leakage.

Expected behavior
I should be able to pass a boolean variable to the module for a stage that defines a custom base path mapping that does not include the stage name.

Example:

```terraform
  api_gateway = {
    name                                = local.api_gateway_name
    hosted_zone_id                      = data.aws_route53_zone.this.id
    custom_domain                       = local.api_domain
    **remove_stage_from_path = true**
    acm_cert_arn                        = module.acm.acm_certificate_arn
    base_path_mapping_active_stage_name = var.spacelift_stack_branch
  }
```

**Comment by cdhesse** [comment]
This is fixed with 5.0.1
