### ISSUE TITLE
Allow REGIONAL custom domain

### ISSUE THREAD

**Issue by skibinstein** [mondelez-ctiso/terraform-aws-api-gateway-v1#26]
Hi,

**Expected Behavior**

by default, the module creates an `EDGE` custom domain.  Creation of `REGIONAL` api gateway resource with Custom Domain Name

**Actual Behavior**

When we create a `REGIONAL` API Gateway, ACM cert outside of us-east-1 and try to create a custom domain, we get the following error. 

`creating API Gateway Domain Name (api.example.com): BadRequestException: Invalid certificate ARN: arn:aws:acm:eu-west-2:1234567890:certificate/400522a7-5e1d-4923-bf24-3d3047e34aef. Certificate must be in 'us-east-1'.`

**Steps to Reproduce**

Configure a `REGIONAL` api gateway and try to create a custom domain name.

**Proposed solution** 

Update aws_api_gateway_domain_name resource with ability to pass endpoint_configuration

```
  endpoint_configuration {
    types = [ "REGIONAL" ]
  }
```

**Comment by cdhesse** [comment]
This has been fixed with release 5.0.1
